# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Software_Custos_definidos.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Software_Custos_Definidos(object):
    def setupUi(self, Software_Custos_Definidos, parent_obj=None):
        self.parent_obj = parent_obj
        Software_Custos_Definidos.setObjectName("Software_Custos_Definidos")
        Software_Custos_Definidos.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Software_Custos_Definidos)
        self.centralwidget.setObjectName("centralwidget")
        self.preco_est1 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est1.setGeometry(QtCore.QRect(190, 140, 113, 20))
        self.preco_est1.setObjectName("preco_est1")
        self.preco_est3 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est3.setGeometry(QtCore.QRect(190, 180, 113, 20))
        self.preco_est3.setObjectName("preco_est3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 140, 101, 16))
        self.label_8.setObjectName("label_8")
        self.custo_pvc_branco = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_branco.setGeometry(QtCore.QRect(190, 10, 113, 20))
        self.custo_pvc_branco.setObjectName("custo_pvc_branco")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 70, 81, 16))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(30, 110, 81, 20))
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 160, 91, 16))
        self.label_7.setObjectName("label_7")
        self.preco_est2 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est2.setGeometry(QtCore.QRect(190, 160, 113, 20))
        self.preco_est2.setObjectName("preco_est2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(26, 10, 141, 20))
        self.label.setObjectName("label")
        self.imposto = QtWidgets.QLineEdit(self.centralwidget)
        self.imposto.setGeometry(QtCore.QRect(180, 110, 151, 20))
        self.imposto.setObjectName("imposto")
        self.custo_pvc_p = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_p.setGeometry(QtCore.QRect(190, 50, 113, 20))
        self.custo_pvc_p.setObjectName("custo_pvc_p")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 50, 141, 16))
        self.label_3.setObjectName("label_3")
        self.frete = QtWidgets.QLineEdit(self.centralwidget)
        self.frete.setGeometry(QtCore.QRect(190, 90, 113, 20))
        self.frete.setObjectName("frete")
        self.custo_pvc_verde = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_verde.setGeometry(QtCore.QRect(190, 30, 113, 20))
        self.custo_pvc_verde.setObjectName("custo_pvc_verde")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 141, 16))
        self.label_2.setObjectName("label_2")
        self.valor_margem = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_margem.setGeometry(QtCore.QRect(190, 210, 113, 20))
        self.valor_margem.setObjectName("valor_margem")
        self.limite_gasto = QtWidgets.QLineEdit(self.centralwidget)
        self.limite_gasto.setGeometry(QtCore.QRect(190, 70, 113, 20))
        self.limite_gasto.setObjectName("limite_gasto")
        self.botao_sair = QtWidgets.QPushButton(self.centralwidget)
        self.botao_sair.setGeometry(QtCore.QRect(240, 320, 75, 23))
        self.botao_sair.setObjectName("botao_sair")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 180, 91, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 210, 81, 16))
        self.label_10.setObjectName("label_10")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(30, 90, 111, 16))
        self.label_4.setObjectName("label_4")
        self.botao_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.botao_calcular.setGeometry(QtCore.QRect(110, 320, 75, 23))
        self.botao_calcular.setObjectName("botao_calcular")
        Software_Custos_Definidos.setCentralWidget(self.centralwidget)

        if self.parent_obj:
            x = self.parent_obj.calculo_coeficiente()
            self.valor_margem.setText(str(x))


        self.retranslateUi(Software_Custos_Definidos)
        QtCore.QMetaObject.connectSlotsByName(Software_Custos_Definidos)

    def retranslateUi(self, Software_Custos_Definidos):
        _translate = QtCore.QCoreApplication.translate
        Software_Custos_Definidos.setWindowTitle(_translate("Software_Custos_Definidos", "Software com Custos definidos"))
        self.label_8.setText(_translate("Software_Custos_Definidos", "Preço da Esteira_1"))
        self.label_6.setText(_translate("Software_Custos_Definidos", "Limite de Gasto:"))
        self.label_5.setText(_translate("Software_Custos_Definidos", "Imposto:"))
        self.label_7.setText(_translate("Software_Custos_Definidos", "Preço da Esteira_2"))
        self.label.setText(_translate("Software_Custos_Definidos", "Custo PVC Branco:"))
        self.label_3.setText(_translate("Software_Custos_Definidos", "Custo PVC Hergonométrico:"))
        self.label_2.setText(_translate("Software_Custos_Definidos", "Custo PVC Verde:"))
        self.botao_sair.setText(_translate("Software_Custos_Definidos", "Sair"))
        self.label_9.setText(_translate("Software_Custos_Definidos", "Preço da Esteira_3"))
        self.label_10.setText(_translate("Software_Custos_Definidos", "Atual margem:"))
        self.label_4.setText(_translate("Software_Custos_Definidos", "Frete:"))
        self.botao_calcular.setText(_translate("Software_Custos_Definidos", "Calcular"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_Software = QtWidgets.QMainWindow()
    ui = Ui_Software_Custos_Definidos()
    ui.setupUi(tela_Software)
    tela_Software.show()
    sys.exit(app.exec_())