# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'software.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Software(object):
    def setupUi(self, Software, parent_obj=None):
        self.parent_obj = parent_obj
        Software.setObjectName("Software")
        Software.resize(693, 443)
        Software.setAutoFillBackground(False)
        Software.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(Software)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.botao_calcular.setGeometry(QtCore.QRect(210, 400, 75, 23))
        self.botao_calcular.setObjectName("botao_calcular")
        self.botao_sair = QtWidgets.QPushButton(self.centralwidget)
        self.botao_sair.setGeometry(QtCore.QRect(420, 400, 75, 23))
        self.botao_sair.setObjectName("botao_sair")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 150, 141, 20))
        self.label.setObjectName("label")
        self.custo_pvc_branco = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_branco.setGeometry(QtCore.QRect(360, 150, 113, 20))
        self.custo_pvc_branco.setObjectName("custo_pvc_branco")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 170, 141, 16))
        self.label_2.setObjectName("label_2")
        self.custo_pvc_verde = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_verde.setGeometry(QtCore.QRect(360, 170, 113, 20))
        self.custo_pvc_verde.setObjectName("custo_pvc_verde")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 190, 141, 16))
        self.label_3.setObjectName("label_3")
        self.custo_pvc_p = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_p.setGeometry(QtCore.QRect(360, 190, 113, 20))
        self.custo_pvc_p.setObjectName("custo_pvc_p")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 240, 111, 16))
        self.label_4.setObjectName("label_4")
        self.frete = QtWidgets.QLineEdit(self.centralwidget)
        self.frete.setGeometry(QtCore.QRect(360, 240, 113, 20))
        self.frete.setObjectName("frete")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(200, 260, 81, 20))
        self.label_5.setObjectName("label_5")
        self.imposto = QtWidgets.QLineEdit(self.centralwidget)
        self.imposto.setGeometry(QtCore.QRect(360, 260, 111, 21))
        self.imposto.setObjectName("imposto")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(200, 220, 81, 16))
        self.label_6.setObjectName("label_6")
        self.limite_gasto = QtWidgets.QLineEdit(self.centralwidget)
        self.limite_gasto.setGeometry(QtCore.QRect(360, 220, 113, 20))
        self.limite_gasto.setObjectName("limite_gasto")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(200, 290, 101, 16))
        self.label_8.setObjectName("label_8")
        self.preco_est1 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est1.setGeometry(QtCore.QRect(360, 290, 113, 20))
        self.preco_est1.setObjectName("preco_est1")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(200, 310, 91, 16))
        self.label_7.setObjectName("label_7")
        self.preco_est2 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est2.setGeometry(QtCore.QRect(360, 310, 113, 20))
        self.preco_est2.setObjectName("preco_est2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(200, 330, 91, 16))
        self.label_9.setObjectName("label_9")
        self.preco_est3 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est3.setGeometry(QtCore.QRect(360, 330, 113, 20))
        self.preco_est3.setObjectName("preco_est3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(200, 360, 81, 16))
        self.label_10.setObjectName("label_10")
        self.valor_margem = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_margem.setGeometry(QtCore.QRect(360, 360, 113, 20))
        self.valor_margem.setObjectName("valor_margem")
        self.boton_open_m2 = QtWidgets.QPushButton(self.centralwidget)
        self.boton_open_m2.setGeometry(QtCore.QRect(240, 60, 191, 23))
        self.boton_open_m2.setObjectName("boton_open_m2")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(10, 80, 831, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, -10, 581, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(30, 30, 601, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(10, 120, 471, 16))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(180, 150, 20, 241))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(187, 135, 331, 31))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(510, 150, 20, 241))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(190, 380, 331, 31))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        Software.setCentralWidget(self.centralwidget)

        self.retranslateUi(Software)
        self.botao_sair.clicked.connect(Software.close)
        self.boton_open_m2.clicked.connect(self.tela_coeficiente)
        # self.botao_calcular.clicked.connect(self.calcular)
        QtCore.QMetaObject.connectSlotsByName(Software)

    def tela_coeficiente(self):
        from coeficiente import Ui_Calcula_Coeficiente
        self.janela = QtWidgets.QMainWindow()
        self.coeficiente = Ui_Calcula_Coeficiente()
        self.coeficiente.setupUi(self.janela)
        self.janela.show()

    def retranslateUi(self, Software):
        _translate = QtCore.QCoreApplication.translate
        Software.setWindowTitle(_translate("Software", "Software"))
        self.botao_calcular.setText(_translate("Software", "Calcular"))
        self.botao_sair.setText(_translate("Software", "Sair"))
        self.label.setText(_translate("Software", "Custo PVC Branco:"))
        self.label_2.setText(_translate("Software", "Custo PVC Verde:"))
        self.label_3.setText(_translate(
            "Software", "Custo PVC Hergonométrico:"))
        self.label_4.setText(_translate("Software", "Frete:"))
        self.label_5.setText(_translate("Software", "Imposto:"))
        self.label_6.setText(_translate("Software", "Limite de Gasto:"))
        self.label_8.setText(_translate("Software", "Preço da Esteira_1"))
        self.label_7.setText(_translate("Software", "Preço da Esteira_2"))
        self.label_9.setText(_translate("Software", "Preço da Esteira_3"))
        self.label_10.setText(_translate("Software", "Atual margem:"))
        self.boton_open_m2.setText(_translate(
            "Software", "Calcular Primeiro a margem de custos"))
        self.label_11.setText(_translate(
            "Software", "Caso o número do valor da margem já seja definido,"))
        self.label_12.setText(_translate(
            "Software", "Olá! caso deseje primeiro calcular ou alterar a margem de custo,"))
        self.label_13.setText(_translate(
            "Software", "  clique no botão abaixo para depois prosseguir com a otimização."))
        self.label_14.setText(_translate(
            "Software", " insira e complete os dados restantes"))

    def retorna_custos_pvc(self, indice):
        if indice > 3 or indice < 0:
            return

        custo1 = float(self.custo_pvc_branco.text())
        custo2 = float(self.custo_pvc_verde.text())
        custo3 = float(self.custo_pvc_p.text())
        vet = [custo1, custo2, custo3]
        return vet[indice]

    def retorna_limite(self):
        limite = float(self.limite_gasto.text())
        return limite

    def retorna_frete(self):
        frete_r = float(self.frete.text())
        return frete_r

    def retorna_imposto(self):
        imposto_r = float(self.imposto.text())
        return imposto_r

    def retorna_preco_esteiras(self, indice):
        if indice > 3 or indice < 0:
            return
        preco1 = float(self.preco_est1.text())
        preco2 = float(self.preco_est2.text())
        preco3 = float(self.preco_est3.text())
        vet_precos = [preco1, preco2, preco3]

        return vet_precos[indice]

    def retorna_margem(self):
        margem_r = float(self.valor_margem.text())
        return margem_r


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Software = QtWidgets.QMainWindow()
    ui = Ui_Software()
    ui.setupUi(Software)
    Software.show()
    sys.exit(app.exec_())
