# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'software.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Software(object):
    def setupUi(self, Software):
        Software.setObjectName("Software")
        Software.resize(693, 443)
        self.centralwidget = QtWidgets.QWidget(Software)
        self.centralwidget.setObjectName("centralwidget")
        self.botao_calcular = QtWidgets.QPushButton(self.centralwidget)
        self.botao_calcular.setGeometry(QtCore.QRect(90, 320, 75, 23))
        self.botao_calcular.setObjectName("botao_calcular")
        self.botao_sair = QtWidgets.QPushButton(self.centralwidget)
        self.botao_sair.setGeometry(QtCore.QRect(220, 320, 75, 23))
        self.botao_sair.setObjectName("botao_sair")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(6, 10, 141, 20))
        self.label.setObjectName("label")
        self.custo_pvc_branco = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_branco.setGeometry(QtCore.QRect(170, 10, 113, 20))
        self.custo_pvc_branco.setObjectName("custo_pvc_branco")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 30, 141, 16))
        self.label_2.setObjectName("label_2")
        self.custo_pvc_verde = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_verde.setGeometry(QtCore.QRect(170, 30, 113, 20))
        self.custo_pvc_verde.setObjectName("custo_pvc_verde")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 50, 141, 16))
        self.label_3.setObjectName("label_3")
        self.custo_pvc_p = QtWidgets.QLineEdit(self.centralwidget)
        self.custo_pvc_p.setGeometry(QtCore.QRect(170, 50, 113, 20))
        self.custo_pvc_p.setObjectName("custo_pvc_p")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 111, 16))
        self.label_4.setObjectName("label_4")
        self.frete = QtWidgets.QLineEdit(self.centralwidget)
        self.frete.setGeometry(QtCore.QRect(170, 90, 113, 20))
        self.frete.setObjectName("frete")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 81, 20))
        self.label_5.setObjectName("label_5")
        self.imposto = QtWidgets.QLineEdit(self.centralwidget)
        self.imposto.setGeometry(QtCore.QRect(160, 110, 151, 20))
        self.imposto.setObjectName("imposto")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 70, 81, 16))
        self.label_6.setObjectName("label_6")
        self.limite_gasto = QtWidgets.QLineEdit(self.centralwidget)
        self.limite_gasto.setGeometry(QtCore.QRect(170, 70, 113, 20))
        self.limite_gasto.setObjectName("limite_gasto")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 140, 101, 16))
        self.label_8.setObjectName("label_8")
        self.preco_est1 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est1.setGeometry(QtCore.QRect(170, 140, 113, 20))
        self.preco_est1.setObjectName("preco_est1")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 91, 16))
        self.label_7.setObjectName("label_7")
        self.preco_est2 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est2.setGeometry(QtCore.QRect(170, 160, 113, 20))
        self.preco_est2.setObjectName("preco_est2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 180, 91, 16))
        self.label_9.setObjectName("label_9")
        self.preco_est3 = QtWidgets.QLineEdit(self.centralwidget)
        self.preco_est3.setGeometry(QtCore.QRect(170, 180, 113, 20))
        self.preco_est3.setObjectName("preco_est3")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 210, 81, 16))
        self.label_10.setObjectName("label_10")
        self.valor_margem = QtWidgets.QLineEdit(self.centralwidget)
        self.valor_margem.setGeometry(QtCore.QRect(170, 210, 113, 20))
        self.valor_margem.setObjectName("valor_margem")
        Software.setCentralWidget(self.centralwidget)

        self.retranslateUi(Software)
        self.botao_sair.clicked.connect(Software.close)
        QtCore.QMetaObject.connectSlotsByName(Software)

    def retranslateUi(self, Software):
        _translate = QtCore.QCoreApplication.translate
        Software.setWindowTitle(_translate("Software", "Software"))
        self.botao_calcular.setText(_translate("Software", "Calcular"))
        self.botao_sair.setText(_translate("Software", "Sair"))
        self.label.setText(_translate("Software", "Custo PVC Branco:"))
        self.label_2.setText(_translate("Software", "Custo PVC Verde:"))
        self.label_3.setText(_translate("Software", "Custo PVC Hergonométrico:"))
        self.label_4.setText(_translate("Software", "Frete:"))
        self.label_5.setText(_translate("Software", "Imposto:"))
        self.label_6.setText(_translate("Software", "Limite de Gasto:"))
        self.label_8.setText(_translate("Software", "Preço da Esteira_1"))
        self.label_7.setText(_translate("Software", "Preço da Esteira_2"))
        self.label_9.setText(_translate("Software", "Preço da Esteira_3"))
        self.label_10.setText(_translate("Software", "Atual margem:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    software = QtWidgets.QMainWindow()
    ui = Ui_Software()
    ui.setupUi(software)
    software.show()
    sys.exit(app.exec_())