# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaInicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TelaInicial(object):
    def setupUi(self, TelaInicial):
        TelaInicial.setObjectName("TelaInicial")
        TelaInicial.resize(907, 600)
        self.centralwidget = QtWidgets.QWidget(TelaInicial)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 40, 71, 51))
        self.label.setObjectName("label")
        self.alterar_margem = QtWidgets.QPushButton(self.centralwidget)
        self.alterar_margem.setGeometry(QtCore.QRect(30, 160, 241, 21))
        self.alterar_margem.setObjectName("alterar_margem")
        self.pagina_software = QtWidgets.QPushButton(self.centralwidget)
        self.pagina_software.setGeometry(QtCore.QRect(30, 190, 331, 23))
        self.pagina_software.setObjectName("pagina_software")
        TelaInicial.setCentralWidget(self.centralwidget)

        self.alterar_margem.clicked.connect(self.alt_margem)
        self.pagina_software.clicked.connect(self.pgn_software)

        self.retranslateUi(TelaInicial)
        QtCore.QMetaObject.connectSlotsByName(TelaInicial)

    def alt_margem(self):
        from coeficiente import Ui_Calcula_Coeficiente
        self.janela = QtWidgets.QMainWindow()
        self.coeficiente = Ui_Calcula_Coeficiente()
        self.coeficiente.setupUi(self.janela)
        self.janela.show()

    def pgn_software(self):
        from software import Ui_Software
        self.janela = QtWidgets.QMainWindow()
        self.software = Ui_Software()
        self.software.setupUi(self.janela)
        self.janela.show()



    def retranslateUi(self, TelaInicial):
        _translate = QtCore.QCoreApplication.translate
        TelaInicial.setWindowTitle(_translate("TelaInicial", "Tela Inicial"))
        self.label.setText(_translate("TelaInicial", "Bem vindo!"))
        self.alterar_margem.setText(_translate("TelaInicial", "Alterar os custos de mão de obra, aluguel e luz"))
        self.pagina_software.setText(_translate("TelaInicial", "Otimizar a quantidade de esteiras com o valor de custo definido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telaInicial = QtWidgets.QMainWindow()
    ui = Ui_TelaInicial()
    ui.setupUi(telaInicial)
    telaInicial.show()
    sys.exit(app.exec_())